### ISSUE TITLE
Suggestion for Organising Algorithms into Subdirectories

### ISSUE THREAD

**Issue by Ramy-Badr-Ahmed** [TheAlgorithms/Fortran#12]
As per the [Contribution Guidelines](https://github.com/TheAlgorithms/Fortran/blob/main/CONTRIBUTING.md#submissions-requirements), I suggest considering moving each algorithm into its own subdirectory within the repository.

This structure would facilitate modularity and clarity. 

For instance, a structure like this:

```
|-- sorts
    -->heap_sort
        --> heap_sort_module.f90
        --> example_usage_heap_sort.f90
        --> tests_heap_sort.f90
    --> quick_sort  
        --> quick_sort_module.f90
        --> example_usage_quick_sort.f90
        --> tests_quick_sort.f90
    --> radix_sort  
        --> radix_sort_module.f90
        --> example_usage_radix_sort.f90
        --> tests_radix_sort.f90
    ⋮
```

**Comment by SatinWukerORIG** [comment]
This is a good petition, but too many files are also redundant. On the The-Algorithms website, only one file is displayed. So we have to put the example usage and algorithms under one file.
I do not know if we should imitate Java and put the test and implementation under two different directories.

What would your suggestion be? I will also contact some other TheAlgorithms admins about this question. 😄

**Comment by Ramy-Badr-Ahmed** [comment]
As already mentioned in the [Contributing Guidelines](https://github.com/TheAlgorithms/Fortran/blob/main/CONTRIBUTING.md#implementation-requirements):

> "The unit of implementation we expect is a [Fortran Module](https://fortran-lang.org/en/learn/best_practices/modules_programs/), the module form mirrors a real-world scenario and makes it easy to use the code from this repository in other projects."

For this reason, I recommend keeping the module file focused solely on the algorithm implementation to ensure it remains clean and portable. This approach allows the module to be easily imported and used in other programs without unnecessary clutter.

However, it still makes sense to separate the test cases into a different directory. As for example usage, it's essentially a quick way to demonstrate how the module works; it could either be omitted or bundled with the test directory.

The newly submitted issue #13 follows a structure that combines the algorithm, example usage, and tests in various parallel directories, which is somewhat similar to the Java repository, where directories are organized by type.

**Comment by SatinWukerORIG** [comment]
That is great! Let's just do it that way 👍
