### ISSUE TITLE
[DOCS] Link to the `main` branch instead of the `master` branch

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Fortran#4]
### Description

The contributing badge on the `README.md` is linking to the `master` branch, which doesn't exist and should instead link to the `main` branch.

_Steps to contribute_

1. Fork the repository [here](https://github.com/TheAlgorithms/Fortran/fork).
2. Create a new branch in your fork named `update_branch_name`.
3. Open the `README.md` file.
4. On line 13, replace `master` with `main`.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/TheAlgorithms/Fortran/compare) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review and check your PR.

If you need any help, let us know about it.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by SatinWukerORIG** [comment]
Thank you for the help and this example issue!
Sorry that I couldn't reply on time because of school.
Completed the fix

**Comment by Panquesito7** [comment]
> Thank you for the help and this example issue! Sorry that I couldn't reply on time because of school. Completed the fix

Thank you, but next time, please leave it open for first-time contributors. 🙂
Offtopic: What's your Discord username? I'd like to contact you over there something related to this repository.

**Comment by SatinWukerORIG** [comment]
No problem. My discord is satinwuker
